"""changed price to amount

Revision ID: 6acad1b56db3
Revises: 9b4f8cfc5da0
Create Date: 2025-04-09 05:21:55.304110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6acad1b56db3'
down_revision = '9b4f8cfc5da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
